spring.application.name=TNTRANSPORT
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/TNTransport
spring.datasource.username=root

upload.path=uploads/

spring.security.oauth2.client.registration.google.client-id=92340409305-svd7dfh8mldeep311pmcefofo8k3fgdr.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile
